### ISSUE TITLE
Does BMXNet support different bit between act and weight?

### ISSUE THREAD

**Issue by tornadomeet** [hpi-xnor/BMXNet#11]
now `act_bit` only allows quantization the same bit width of act & weight, so does BMXNet support different bit between act and weight?  or it will support it in the future? 

thanks.

**Comment by mtin** [comment]
we do support setting different bit widths for the QActivation and QConvolution layer - as an example, have a look at [smd_hpi/examples/binary_mnist/train_val.py](https://github.com/hpi-xnor/BMXNet/blob/master/smd_hpi/examples/binary_mnist/train_val.py)

near the top you can see the constants BITW and BITA setting the bit width for weights and activation, respectively!

just as a side note: when using variable bit width (!=1), BMXNet will not be able to utilize our optimized bit convolution kernels.

**Comment by tornadomeet** [comment]
got it, Thanks @mtin
