### ISSUE TITLE
A question about realization

### ISSUE THREAD

**Issue by cctgem** [hpi-xnor/BMXNet#12]
I find that all layers only store quantized weights.
It's different from Dorefa-net, which also store origin weights and update them.
Will this affect the result?

**Comment by yanghaojin** [comment]
Hi,
yes in our implementation we only store quantized weights, it may differ to Dorefa-net, I'm not sure for this. But I think if we always additionally save the original weights in 32 bit, then there will be no benefit for saving storage space. From the first feeling, I don't think this will affect the accuracy significantly, we will further study on this.
