### ISSUE TITLE
AttributeError: 'module' object has no attribute 'QActivation'

### ISSUE THREAD

**Issue by springishere** [hpi-xnor/BMXNet#13]
I am having issue as shown in the topic, it seems that the smd_hpi/src files are not get compiled.
I am using Ubuntu 16.04. I don't see these .o files under build/.
I did follow the steps in the Setup section. The changes are:
- make/config.mk: USE_MKL2017 = 1, USE_MKL2017_EXPERIMENTAL = 1, USE_BLAS = openblas (Note USE_CUDA is 0 as original)
- the main CMakeLists.txt: line 14 changed USE_CUDA defaults to OFF, otherwise compile issue.

**Comment by fye881** [comment]
I added this to the main CMakeLists.txt file get around:
@@ -435,7 +435,7 @@ else()
   if(UNIX)
     add_library(mxnet_static STATIC ${SOURCE})
     # Need an arbitrary source file to trigger CMake to build the library
-    add_library(mxnet SHARED)
+    add_library(mxnet SHARED ${SOURCE})
     # This has prolems, as it adds libmxnet_static to INTERFACE_LINK_LIBRARIES

I also set the USE_CUDA to default OFF in the same file, because I would like to get perf number of CPU.

However I am now having lots of undefined reference, like dnnDelete_F32. I guess the intel MKLML library may not be included in the build.

**Comment by saicoco** [comment]
You can try cmake, and config PYTHONPATH and LD_LIBRARY_PATH

**Comment by springishere** [comment]
that's next step, after it's compiled. I don't see the object files under build/smd_hpi/src)

**Comment by springishere** [comment]
The CMakeLists.txt file under smd_hpi is empty, there's also no Makefile. The main Makefile didn't reference smd_hpi directory.
If I add to the main Makefile the smd_hpi directory rule, it will compile and then throw out other error.
I wonder how the files under smd_hpi/src would get compiled?

**Comment by yanghaojin** [comment]
Hi,
cmake is currently the standard compiling tool for BMXNet.
You can find the cmake definition in the main CMakeLists.txt file [link](https://github.com/hpi-xnor/BMXNet/blob/master/CMakeLists.txt#L278).

**Comment by springishere** [comment]
yes I noticed that, I also printed out (message) the SOURCE and see the files are there, however they are not get compiled.
I wonder if it's because I set USE_CUDA to OFF?

**Comment by yanghaojin** [comment]
no, I don't think USE_CUDA made the problem. was your cmake configuation and cmake generation successful?

**Comment by springishere** [comment]
I found the reason, stupid mistake, I was doing make in the root directory instead of the build directory, that's why I need to make changes to the main makefile to compile smd_hpi directory. Now everything makes sense.

**Comment by VintonyPadmadiredja** [comment]
Hi,

I've followed the steps to install BMXNet however I get this error when try use it in python.
What I did were:
- mkdir build && cd build
- ccmake .. (Without CUDA as it gives me compilation errors. What version of CUDA and cuDNN should I be running? Currently running 8.0 and 6.0 - tried using 5.1 but no difference) 
Also is this a problem?:
>  You have called ADD_LIBRARY for library mxnet without any source files. This
>  typically indicates a problem with your CMakeLists.txt file

Then,
- make -j 'nproc' (Still within build directory)

I then add these
- LD_LIBRARY_PATH=/path/to/mxnet-root/build
- PYTHONPATH=/path/to/mxnet-root/python 

Other mxnet methods appears to work but the Q methods give me 'module' object has no attribute 'QActivation' , etc.

Any help? Thanks!

**Comment by yanghaojin** [comment]
Hi,
to your questions:

1. mkdir build && cd build  
**solution** mkdir build/Release && cd build/Release (which is a more common way, and doing this you may have less problem with the python binding. I will update the document later.)

2. ccmake .. (Without CUDA as it gives me compilation errors. What version of CUDA and cuDNN should I be running? Currently running 8.0 and 6.0 - tried using 5.1 but no difference)
**solution** with CUDA support, its better to use cuda9 and cudnn7 for the current release

3. Also is this a problem?:
You have called ADD_LIBRARY for library mxnet without any source files. This
typically indicates a problem with your CMakeLists.txt file
**solution** this is a warning, the proj can still be compiled

4. python binding
**solution** pls refer to the [python binding install section of the mxnet docu](https://mxnet.incubator.apache.org/install/index.html)

please try out the points mentioned above, feel free to report if any further problem occurs.

best
HJ

**Comment by VintonyPadmadiredja** [comment]
Hi, 
Thank you! Those solutions have solved the problems for the python bindings.

However I'm still having problems compiling with CUDA and cuDNN. Here is a bit of the long error messages I get:

> ...
> Error limit reached.
> 100 errors detected in the compilation of "/tmp/tmpxft_00002145_00000000-7_utils.cpp1.ii".
> Compilation terminated.
> CMake Error at cuda_compile_generated_utils.cu.o.cmake:264 (message):
>   Error generating file
>   /path/to/mxnet/build/Release/CMakeFiles/cuda_compile.dir/src/common/./cuda_compile_generated_utils.cu.o
> 
> 
> make[2]: *** [CMakeFiles/cuda_compile.dir/src/common/cuda_compile_generated_utils.cu.o] Error 1
> /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h(432): error: identifier "nullptr" is undefined
> 
> /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h(432): error: expected a ";"
> 
> /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++config.h(190): error: expected a ";"
> 
> /usr/include/c++/4.8/exception(63): error: expected a ";"
> 
> /usr/include/c++/4.8/exception(68): error: expected a ";"
> 
> /usr/include/c++/4.8/exception(76): error: expected a ";"
> 
> /usr/include/c++/4.8/exception(83): error: expected a ";"
> 
> /usr/include/c++/4.8/exception(93): error: expected a "{"
> 
> /usr/include/c++/4.8/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"
> 
> /usr/include/c++/4.8/bits/exception_ptr.h(64): error: expected a "{"
> 
> /usr/include/c++/4.8/bits/exception_ptr.h(79): error: expected a ";"
> 
> /usr/include/c++/4.8/bits/exception_ptr.h(81): error: expected a ";"
> 
> /usr/include/c++/4.8/bits/exception_ptr.h(82): error: expected a ";"
> 
> /usr/include/c++/4.8/bits/exception_ptr.h(84): error: expected a ";"
> 
> /usr/include/c++/4.8/bits/exception_ptr.h(86): error: declaration is incompatible with previous "std::current_exception"
> (64): here
> ...

Thank you

**Comment by yanghaojin** [comment]
I think this is not a BMXNet specific problem, pls try to follow the tutorials of mxnet for cuda installation [here](https://mxnet.incubator.apache.org/install/index.html)
