### ISSUE TITLE
Could not turn off USE_CUDA

### ISSUE THREAD

**Issue by JiangPQ** [hpi-xnor/BMXNet#15]
There is a CMake error while compiling on raspberrypi:
CMake Error at mshadow/cmake/mshadow.cmake:46 (message):
  -- CUDA is disabled.
Call Stack (most recent call first):
  CMakeLists.txt:126 (include)

Operating System:
raspbian

I've changed something in CMakeLists.txt and cmake again but it didn't work:

mxnet_option(USE_CUDA             "Build with CUDA support"   OFF)
mxnet_option(USE_CUDNN            "Build with cudnn support"  OFF) 

I use MESSAGE to print the variable USE_CUDA while cmake, it is still ON.

Can you tell me where is the right place to set USE_CUDA OFF?

**Comment by yanghaojin** [comment]
hi，
pls make sure you dont have the same issue as in this track: https://github.com/hpi-xnor/BMXNet/issues/13

**Comment by mtin** [comment]
hey JianqPQ, you should not have to change the CMakeLists.txt file to disable CUDA. If you already ran cmake, then there should be a CMakeCache.txt file with the settings cmake determined. you can edit the value of USE_CUDA in that file.

Alternatively, you could use a cmake with a user interface, like ccmake to comfortably change the options.

**Comment by JiangPQ** [comment]
Thank you for your reply!
I cleanned all the cmake generated files and cmake again then it works.
