### ISSUE TITLE
Upgrade to MXNet 0.12.1 and beyond

### ISSUE THREAD

**Issue by ehsanmok** [hpi-xnor/BMXNet#18]
Hi

Thanks for providing this great tool on top of MXNet. I'd like to know whether you have any plans to upgrade to the latest version of MXNet (now 0.12.1, and 1.0.0 to be come) to use better features of gluon for example? or if someone wants to do so, is there any recommendation asides from watching collisions, etc.?

**Comment by yanghaojin** [comment]
Hi ehsanmok,
yes, upgrade to the latest MXNet is already planned. Since our code is relatively separated, so far there should be no big problem with this.
