### ISSUE TITLE
Cannot Build with USE_DIST_KVSTORE=ON

### ISSUE THREAD

**Issue by ehsanmok** [hpi-xnor/BMXNet#19]
## Environment info
Operating System: Ubuntu 16.04 
gcc, g++ 5.4.0
protoc 3.5.0

Built protobuf from the source: https://github.com/google/protobuf/tree/master/src
and have all the required env variables:

PROTOBUF_INCLUDE_DIR="/usr/include/"
PROTOBUF_LIBRARY="/usr/lib/libprotobuf.so" 
PROTOBUF_LIBRARY_DEBUG="/usr/lib/libprotobuf.so"
PROTOBUF_LITE_LIBRARY="/usr/lib/libprotobuf-lite.so"  
PROTOBUF_LITE_LIBRARY_DEBUG="/usr/lib/libprotobuf-lite.so"   
PROTOBUF_PROTOC_EXECUTABLE="/usr/bin/protoc"
PROTOBUF_PROTOC_LIBRARY="/usr/lib/libprotoc.so"
PROTOBUF_PROTOC_LIBRARY_DEBUG="/usr/lib/libprotoc.so"

## Error Message:

You have called ADD_LIBRARY for library mxnet without any source files. This typically indicates a
problem with your CMakeLists.txt file 

 CMake Error at CMakeLists.txt:471 (target_link_libraries):
The "debug" argument must be followed by a library.

## Minimum reproducible example

USE_CUDA=0, USE_OPENCV=1 and USE_DIST_KVSTORE=1
And when I remove that line in CMakeList.txt the tests fails!
Any idea what might be causing the problem?

This was also reported [here](https://github.com/apache/incubator-mxnet/issues/7519) with no solution!

**Comment by ehsanmok** [comment]
I could build mxnet==0.12.1 from source with USE_CUDA=0  USE_CUDNN=0 and USE_DIST_KVSTORE=1 though. I figured out my main CMakefileList.txt was changed and I cloned a new one. Also had some proxy issue for building ps-lite/make/dep.mk which I resolved. 
I know this issue might not be very related to bmxnet specific feature, but I want to know if you are able to build distributed bmxnet. 
Thanks!

**Comment by yanghaojin** [comment]
Hi ehsanmok,
the current BMXNet version is based mxnet==0.1.0 and CUDA 8.0. 
We are working on the upgrade to mxnet1.0, will release it soon, stay tuned. 
HJ

**Comment by ehsanmok** [comment]
Hi @yanghaojin 
Do you know of any time estimate when v1.0 will be released? The current version is too much of headache.

**Comment by yanghaojin** [comment]
Hi, 
I hope the upgrade could be finished in the next week. We are working on the model testing.
After the upgrade we can take advantages of cudnn to train a BNN, so this could largely improve the training speed.

**Comment by ehsanmok** [comment]
@yanghaojin  that's great to hear! looking forward to it.
