### ISSUE TITLE
any plan to store parameters in 8-bits unsigned char?

### ISSUE THREAD

**Issue by vsooda** [hpi-xnor/BMXNet#2]
> The quantization on bit widths ranging from 2 to 31 bit is available mainly for scientific purpose. There is no speed or memory gain (rather the opposite since there are conversion steps) as the quantized values are still stored in full precision float variables.

to store all 2 to 31 bit to files maybe  difficult. Any plan to support 8 bit parameter storage?

**Comment by vsooda** [comment]
need to implement a `model_converter` and functions(such as `QConvolutionForward`) supporting 8 bit compute ?

**Comment by mtin** [comment]
hey, I know you closed this already, just a short remark: mxnet already supports 8 bit data types in various operators, and also saving and loading them. You can use the 'cast' operator in the beginning with the parameter dtype='uint8' to try this! cheers

**Comment by vsooda** [comment]
@mtin Thanks for your kind reminder.
