### ISSUE TITLE
Is Amalgamation method supported by BMXNet?

### ISSUE THREAD

**Issue by PhanTask** [hpi-xnor/BMXNet#20]
Haven't try it yet, but putting original MXNet models into mobile devices(say Android)  using the amalgamation method is a error-prone thing. So is there anything needed to be paid extra attention when porting BMXNet models?

**Comment by mtin** [comment]
your question is very reasonable, we had our fair share of issues with the amalgamation process. 
BMXNet has been running on both iOS and Android, we modified the amalgamation scripts to include our sources and added some fixes, e.g. enabling OpenMP on Android and scripts to support Apples GEMM implementation (Accelerate).
Generally speaking it should work, though we are currently in the process of upgrading to mxnet v1.0.0 and have not tested the amalgamation recently. I would encourage you to try for yourself and report back if you find any issues!
