### ISSUE TITLE
Resnet-binary not working on 32 bit system

### ISSUE THREAD

**Issue by ahuynh227** [hpi-xnor/BMXNet#23]
I used resnet-binary symbol to train on 224x224 images, converted the model and tried the inference on multiple systems. The model works fine on 64 bit system but gives the same prediction score for all the samples tested on 32 bit. I was wondering what the differences are between 64 and 32 and if there is anything I can do to fix that? 
Thanks in advance!

**Comment by yanghaojin** [comment]
congras that it works for 64bit :-).
for 32bit you dont need to retrain the model, but recompile bmxnet with setting the cmake option  BINARY_WORD_TYPE to uint32. then run the model converter to create a 32bit model, use it for 32bit devices. The difference between 32 and 64bit is which container (uint32 or uint64) we use to store the weights,and how we concatinate the weights.

**Comment by ahuynh227** [comment]
Recompiled the code and got it working. Thanks for your help!
