### ISSUE TITLE
QActivation backward_only problems

### ISSUE THREAD

**Issue by jacky4323** [hpi-xnor/BMXNet#24]
Hi guys,

May I ask some questions?

question1: ALL Q series layers are all coding by c++ code ?
question2: QActivation layers with  backward_only=True can back propagate  quantization gradient,it means that you didn't write the calculate gradient of quantization function  code in Qconvolution,Qfullconnectlayer?

thanks a lot

Best Regards,
Peng

**Comment by yanghaojin** [comment]
Hi Peng,
to your questions,
Q1: yes, the implementation is in C++, otherwise we cannot create the binarized models, you can check the model size [here](https://github.com/hpi-xnor/BMXNet/tree/master/smd_hpi/binary_models)
Q2: yes.

**Comment by jacky4323** [comment]
thank you for your reply!!
