### ISSUE TITLE
Stucked in ccmake: selected BINARAY_WORD_TYPE

### ISSUE THREAD

**Issue by ysh329** [hpi-xnor/BMXNet#3]
Stucked in `ccmake`: selected BINARAY_WORD_TYPE as below:
I only can switch `BINARAY_WORD_TYPE` but can't continue
![ccmake](https://cloud.githubusercontent.com/assets/7320657/26675269/e57985be-46f5-11e7-944e-36346972cf96.png)

**Comment by mtin** [comment]
could you elaborate, what do you mean by you are stuck?

just set some options (enter to select/set entry, arrow keys to navigate) and press 'c' to configure and at the end 'g' to generate the makefiles.

**Comment by ysh329** [comment]
Excuse me, I'm not familar this `ccmake`. Now it's okay!
Greatly thanks for your replying.
