### ISSUE TITLE
Plan to merge to upstream?

### ISSUE THREAD

**Issue by mli** [hpi-xnor/BMXNet#4]
Many thanks for the great work! I'm wondering if you have any plan to merge your codes to upstream `dmlc/mxnet`?

**Comment by yanghaojin** [comment]
Hi Mu,
We are happy to do that if this implementation becomes more stable. Of course we may then need your help to do this in a more appropriate way.
HJ

**Comment by smolix** [comment]
Hi Hangjao, I'll be in Berlin in a week. Do you want to catch up? Alex.

**Comment by yanghaojin** [comment]
Hi Alex,
we are very exited to meet you in Berlin, or even honored to invite you to HPI (Potsdam, Griebnitzsee) if possible. We could further talk about it using email haojin.yang@hpi.de .
Best
HJ

**Comment by Jopyth** [comment]
Closing this, since we only support the new version from now on: https://github.com/hpi-xnor/BMXNet-v2
