### ISSUE TITLE
Where do you implement XNOR networks?

### ISSUE THREAD

**Issue by haithanhp** [hpi-xnor/BMXNet#44]
Hi @yanghaojin 

Thanks for your great work. In the paper, you claimed that BMXNet uses the algorithm of XNOR networks. Could you show me where you did implement for Convolution layers? In addition, could you tell me which binary imagenet models you applied XNOR networks for binarizing? 

Thanks,
Hai

**Comment by yanghaojin** [comment]
https://github.com/hpi-xnor/BMXNet/tree/master/smd_hpi
