### ISSUE TITLE
No difference in binarized and full-precision LeNet model size

### ISSUE THREAD

**Issue by jonkoi** [hpi-xnor/BMXNet#47]
I tried your binarized mnist Lenet example and trained a binarized model and a normal model. The resulting binarized/normal params files are 4.6MB/4.6MB instead of 206kB/4.6MB in the paper. I saw your pretrained binarized model really achieved 206kB.

Am I missing something? Is there a compression step?

**Comment by jonkoi** [comment]
Sorry, i did not read about the model converter part. Trying it out, closing the issue.

**Comment by kaka-lin** [comment]
sorry
Have you solved the problem？
