### ISSUE TITLE
depth-wise convolution support

### ISSUE THREAD

**Issue by jacky4323** [hpi-xnor/BMXNet#51]
Hi @yanghaojin ,

Did you have implemented depth-wise convolution for the binarized model such as mobilenet?
Thanks!

**Comment by jonkoi** [comment]
I second this. I am hoping to be able to binarize mobilenet.

**Comment by yanghaojin** [comment]
mobilenet and architectures with google bottlenecks design or other net shrinking techniques are not appropriate for binarization. One cannot expect to take advantages from both styles of network architectures.
More details could be found in this paper: https://arxiv.org/abs/1809.10463
