### ISSUE TITLE
mxnet error: redeclaration of 'kNone' when setting USE_CPP_PACKAGE = 1

### ISSUE THREAD

**Issue by iamweiweishi** [hpi-xnor/BMXNet#54]
Hi, I followed your setup instructions and could build the project successfully.
But when I set USE_CPP_PACKAGE = 1, the error occurs:

![default](https://user-images.githubusercontent.com/23145532/52161749-faa54b80-2704-11e9-8955-eec8660f4bda.JPG)

The redeclaration looks like this:
enum class QConvolutionScalingMode {
  kNone = 0,
  kBackward = 1,
  kForward = 2,
  kNone = 3
};

I tried to delete one 'kNone' in line 6866 of 'mxnet-cpp/op.h'. But the file seems to be generated by a wrapper. So the modification is useless.
Any help would be greatly appreciated.
Thank you.

**Comment by yanghaojin** [comment]
Hi, would you like to check the new branch of BMXNet, which support Gluon and latest MXNet version:
https://github.com/hpi-xnor/BMXNet-v2
