### ISSUE TITLE
Any pre-built dynamic library or executable file for andriod?

### ISSUE THREAD

**Issue by blueardour** [hpi-xnor/BMXNet#55]
Hi, Dear HPI team,

Thanks for the wonderful project. I'm conducting some network binrarization research and want to compare the speed of binray network versus its FP32 counterpart on cellphone. This repository might provide a convienent framework for testing. However, it is a long way to build the OpenBlas and the amalgamation module for ARM platforms. I've tried so for a long time but ony got a lot of errors.
I wonder if you have already compiled some library to run on Android platform. For example, the  jni_libmxnet_predict.so mentioned in the project, by which I could call for speedup testing.

Thanks very much.

**Comment by blueardour** [comment]
Hi, I've successfully built the OpenBlas, however the amalgamation submodule seemed not to be built.

A lot of header files were not found...

**Comment by Jopyth** [comment]
Closing this, since we only support the new version from now on: https://github.com/hpi-xnor/BMXNet-v2
