### ISSUE TITLE
XNOR-Net implementation

### ISSUE THREAD

**Issue by kaivu1999** [hpi-xnor/BMXNet#60]
## Description
If I am not wrong BMXNet follows XNOR implementation  right ?
For reference this is the image from XNOR paper.

![XNOR-Net](https://user-images.githubusercontent.com/35027192/61712507-2203d980-ad74-11e9-9540-c951d4ae326a.png)

If yes, then
Where can I find these multiplications ( Output_Matrix* k * alpha ) in the code ?

## Code

1. I was looking in these files [q_convolution-inl.h](https://github.com/hpi-xnor/BMXNet/blob/master/smd_hpi/src/q_convolution-inl.h) and [q_convolution_v1-inl.h](https://github.com/hpi-xnor/BMXNet/blob/master/smd_hpi/src/q_convolution_v1-inl.h)
 2. Also, what is the difference between these two files and which one is used ?

Can you please help me @yanghaojin ?
Thanking you in advance !

**Comment by Jopyth** [comment]
Closing this, since we only support the new version from now on: https://github.com/hpi-xnor/BMXNet-v2
