### ISSUE TITLE
Plans to compare performance under more configurations

### ISSUE THREAD

**Issue by dongxiao92** [hpi-xnor/BMXNet#7]
Thanks for your great job about implementation of all this algotithms and integrating them in MXNet.
I'm curious about performance in more convolution configurations.For instance,3*3 convolutions are often used in CNNs and there is winograd fast convolution algorithm for doing calculations.
As I know,Intel MKL、NN-PACK and cudnn(starting from v5) have used fast convolution algorithm instead of im2col+gemm in most 3*3 convolution configurations. So do you have any plans about comparing performance in this situations?
Thanks a lot

**Comment by yanghaojin** [comment]
Hi,
thank you for your comment, we will continue this work to further improve the performance, and also consider to compare with the fast convolution algorithm (maybe we could also take advantages 
 with it). In this implementation we actually paid more attention on how to reduce the model size and enable the application of complicated deep models on mobile devices; and how to make the binary components be used as easy as possible. Of course further speedup is also our next goal.

**Comment by dongxiao92** [comment]
thank you for your reply.cheers~
