### ISSUE TITLE
image-classification-predict

### ISSUE THREAD

**Issue by zhoushiqi123** [hpi-xnor/BMXNet#8]
I use smd_hpi/examples/binary-imagenet1k/predict-cpp/image-classification-predict and a pretrained binary model to classify a image
when I use binarized_imagenet-resnet18-64bit-0040.params
the log is
model/Inception/Inception-BN-symbol.json ... 25049 bytes
model/Inception/Inception-BN-0126.params ... 3553824 bytes
model/Inception/mean_224.nd ... 602188 bytes
Segmentation fault
there is a Segmentation fault error.

when i use binarized_imagenet-resnet18-64bit-1st-stage-fullprecision-0038.params
whichever image I used to classify the log is
Accuracy[988] = 0.00000000
Accuracy[989] = 0.00000000
Accuracy[990] = 0.00000000
Accuracy[991] = 0.00000000
Accuracy[992] = 0.00000000
Accuracy[993] = 0.00000000
Accuracy[994] = 0.00000000
Accuracy[995] = 0.00000000
Accuracy[996] = 0.00000000
Accuracy[997] = 0.00000000
Accuracy[998] = 0.00000000
Accuracy[999] = 0.00000000
Best Result: [ tennis ball] id = 852, accuracy = 1.00000000

Any help would be appericated!

**Comment by yanghaojin** [comment]
Thank you for your report, we didn't adapt the "predict-cpp/image-classification-predict" for using binary model. We are working on this issue and will update the corresponding file in the next commits.

**Comment by ahuynh227** [comment]
@yanghaojin Do you have any updates on this using binary model?
