### ISSUE TITLE
is there any bit-packing implementation?

### ISSUE THREAD

**Issue by huyanyan008** [hpi-xnor/BMXNet#9]
I just have a quick question:
Did you implement any bit-packing after the 1-bit quantization and if so, would you please direct me to the source code? 
Thanks in advance.

**Comment by mtin** [comment]
Sure! The methods `get_binary_col` and `get_binary_row` are used to binarize and pack inputs and weights, respectively. The result is a `BINARY_WORD` which has a width of either 32 or 64 bit (depending on your cmake settings) and contains the same amount of packed 1-bit values.

Find the methods at `smd_hpi/src/xnor_cpu.h.`
